name: Desafio backend

on: push

jobs:
  desafio-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
